services:
  api:
    build: .
    ports:
      - 8000:8000  # redirect the port <port on localhost>:<port on container>
    env_file:
      - ./.env
    environment:
      DATABASE_HOSTNAME: postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_db:/var/lib/postgresql/data # where db data is stored

volumes:
  postgres_db: # volume name