name: Build and Deploy Code
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]
jobs:
  job1: 
    runs-on: ubuntu-lastest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to emmanuel
        run: echo "hello emmanuel"